apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: adopt-aws-assume-role-role
  namespace: aws-assume-role
spec:
  aws:
    arn: arn:aws:iam::{{ .Values.accountId }}:role/aws-assume-role-role
  kubernetes:
    group: iam.services.k8s.aws
    kind: Role
    metadata:
      name: aws-assume-role-role
      namespace: aws-assume-role
