apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-assume-role-controller
  labels:
    app.kubernetes.io/component: aws-assume-role-controller
    app.kubernetes.io/name: aws-assume-role-controller
subjects:
  - kind: ServiceAccount
    name: aws-assume-role-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  name: aws-assume-role-controller
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
