apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-assume-role-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      apps.kubernetes.io/name: aws-assume-role-controller
  template:
    metadata:
      labels:
        apps.kubernetes.io/name: aws-assume-role-controller
    spec:
      containers:
        - name: aws-assume-role-controller
          image: "wdonne/pincette-aws-assume-role:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- if .Values.command }}
          command: {{ toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{ toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- if .Values.ports }}
          ports: {{ toYaml .Values.ports | nindent 12 }}
          {{- end }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      serviceAccountName: aws-assume-role-controller
