apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-assume-role-controller
  namespace: aws-assume-role
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.accountId }}:role/aws-assume-role-role
  labels:
    app.kubernetes.io/component: aws-assume-role-controller
    app.kubernetes.io/name: aws-assume-role-controller
