apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-assume-role-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: aws-assume-role-controller
    app.kubernetes.io/name: aws-assume-role-controller
