apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awsassumeroles.pincette.net
spec:
  group: pincette.net
  names:
    kind: AWSAssumeRole
    plural: awsassumeroles
    singular: awsassumerole
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.health.status
          name: Health
          type: string
        - jsonPath: .status.phase
          name: Phase
          type: string
        - jsonPath: .status.status
          name: Health
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                durationSeconds:
                  type: integer
                ecrRepositoryUrl:
                  type: string
                roleName:
                  type: string
                secretName:
                  type: string
                secretType:
                  enum:
                    - EcrDockerConfigJson
                    - File
                    - Map
                  type: string
              required:
                - roleName
                - secretName
                - secretType
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        type: string
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
                health:
                  properties:
                    status:
                      type: string
                  type: object
                phase:
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
